# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb5d28c5f5284a590155d844b99e75b5c3dbba64142cc709a21765ae22cbb421e53245de2aac3217ebe08a036d5200731102c2cc5c23d261629baf0b7ce7ac3b

test:
  secret_key_base: 7978eb805f95f60ecbe21d75dc1a048b5a1cdf824f0c348b937a69bf7517955afbcf35c64a7819c4d267247580fba58c4f344564954a92bab5b44319be1edabf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
